# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
        
    - name: Test
      run: go test -v ./...

    - name: Build Linux
      run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o build/c2k-linux -ldflags="-X main.Version=${{ github.event.release.tag_name }}" github.com/Stexxe/c2k/cmd/c2k
    - name: Build OSX Intel
      run: CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o build/c2k-osx-amd64 -ldflags="-X main.Version=${{ github.event.release.tag_name }}" github.com/Stexxe/c2k/cmd/c2k
    - name: Build OSX Apple silicon
      run: CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -o build/c2k-osx-arm64 -ldflags="-X main.Version=${{ github.event.release.tag_name }}" github.com/Stexxe/c2k/cmd/c2k
    - name: List compiled binaries
      run: ls -la ./build

    - name: Upload the c2k binaries
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
        file: ./build/c2k-*
        file_glob: true
   
